{% set name = "okta-jwt-verifier" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/okta_jwt_verifier-{{ version }}.tar.gz
  sha256: bd3b3280738bf8de1b40fffcc1a34b5ae442d25490b7049eeadaed0565957b7e

build:
  noarch: python
  script:
    - cp -R {{ RECIPE_DIR }}/LONG_DESCRIPTION.md {{ SRC_DIR }}/LONG_DESCRIPTION.md # [unix]
    - echo f | xcopy /f /y /S %RECIPE_DIR%\LONG_DESCRIPTION.md %SRC_DIR%\LONG_DESCRIPTION.md # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - pyjwt >=2.8.0,<3.0.0
    - retry2 >=0.9.5,<0.10.0
    - python >={{ python_min }}
    - acachecontrol >=0.3.6,<0.4.0
    - aiohttp
    - python-jose
    - retry

test:
  imports:
    - okta_jwt_verifier
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/okta/okta-jwt-verifier-python
  summary: Okta JWT Verifier
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
