{% set name = "okta-jwt-verifier" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/okta_jwt_verifier-{{ version }}.tar.gz
  sha256: 172cf6d9fb8e0c1bcb67a826c604ddec1b59703b5599d74bfde21f5b777647d4

build:
  noarch: python
  script:
    - cp -R {{ RECIPE_DIR }}/LONG_DESCRIPTION.md {{ SRC_DIR }}/LONG_DESCRIPTION.md  # [unix]
    - echo f | xcopy /f /y /S %RECIPE_DIR%\LONG_DESCRIPTION.md %SRC_DIR%\LONG_DESCRIPTION.md  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core
  run:
    - python >=3.8
    - acachecontrol >=0.3.5,<0.4.0
    - pyjwt >=2.8.0,<3.0.0
    - retry
    #- retry2 >=0.9.5,<0.10.0 # # Not Available
    #- aiohttp # Not Needed
    #- python-jose # Not Needed

test:
  imports:
    - okta_jwt_verifier
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/okta/okta-jwt-verifier-python
  summary: Okta JWT Verifier
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
