{% set name = "okta-jwt-verifier" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/okta_jwt_verifier-{{ version }}.tar.gz
  sha256: 55659d490412261abb26a481c0cab7f23b514d25e8c9cd8483f18ebb511e4cea

build:
  noarch: python
  script:
    - cp -R {{ RECIPE_DIR }}/LONG_DESCRIPTION.md {{ SRC_DIR }}/LONG_DESCRIPTION.md # [unix]
    - echo f | xcopy /f /y /S %RECIPE_DIR%\LONG_DESCRIPTION.md %SRC_DIR%\LONG_DESCRIPTION.md # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - retry2 >=0.9.5,<0.10.0
    - python >={{ python_min }}
    - pyjwt >=2.8.0,<3.0.0
    - acachecontrol >=0.3.6,<0.4.0
    - retry  #2 >=0.9.5,<0.10.0

test:
  imports:
    - okta_jwt_verifier
  commands:
    #- pip check fails for retry2 dependency
    - python -c "assert __import__('okta_jwt_verifier').__version__ == '{{ version }}'"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/okta/okta-jwt-verifier-python
  summary: Okta JWT Verifier
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
